<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query\SelectQuery;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Event\Event;
use Cake\Event\EventInterface;
use Cake\Event\EventManager;
use Cake\Datasource\EntityInterface;
use Cake\Log\Log;
use App\Event\DomainEvents;
use ArrayObject;

/**
 * ProductsTable — Phase 5: Behaviors + Custom Finders + Events
 *
 * Uses SlugBehavior and SoftDeleteBehavior to demonstrate how
 * behaviors extend table functionality without subclassing.
 *
 * BEHAVIORS ATTACHED:
 *   Timestamp  → auto created/modified
 *   Slug       → auto-generates slug from name
 *   SoftDelete → delete() sets deleted_at instead of removing row
 *
 * CUSTOM FINDERS:
 *   find('available')     → in-stock, not soft-deleted
 *   find('byCategory')    → filtered by category
 *   find('priceRange')    → filtered by min/max price
 *   find('lowStock')      → stock <= threshold
 *   find('search')        → text search
 */
class ProductsTable extends Table
{
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('products');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        // =====================================================================
        // BEHAVIORS — Phase 5
        // =====================================================================

        // 1. TimestampBehavior: auto-manages created/modified
        $this->addBehavior('Timestamp');

        // 2. SlugBehavior: auto-generates slug from 'name' column
        //    "My Product" → "my-product" before each save
        //    Config options override defaults from SlugBehavior::$_defaultConfig
        $this->addBehavior('Slug', [
            'field'  => 'name',   // Source: generate slug from this field
            'slug'   => 'slug',   // Target: store in this column
            'unique' => true,     // Append -1, -2 if slug already taken
        ]);

        // 3. SoftDeleteBehavior: delete() sets deleted_at instead of DELETE SQL
        //    Requires: products table has a nullable 'deleted_at' DATETIME column
        $this->addBehavior('SoftDelete', [
            'field'      => 'deleted_at',
            'autoFilter' => true, // Automatically exclude soft-deleted from find()
        ]);

        // =====================================================================
        // ASSOCIATIONS — Phase 5: All types demonstrated
        // =====================================================================

        // belongsTo: Product BELONGS TO one Category
        //   FK: products.category_id → categories.id
        //   joinType INNER means products without a category won't appear in queries
        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType'   => 'LEFT', // LEFT JOIN: include products even without category
        ]);

        // belongsTo: Product BELONGS TO one Brand
        //   FK: products.brand_id → brands.id
        $this->belongsTo('Brands', [
            'foreignKey' => 'brand_id',
            'joinType'   => 'LEFT',
        ]);

        // hasMany: Product HAS MANY OrderItems
        //   FK: order_items.product_id → products.id
        //   'dependent' => false: deleting a product does NOT delete order history
        $this->hasMany('OrderItems', [
            'foreignKey' => 'product_id',
            'dependent'  => false,
        ]);
    }

    // =========================================================================
    // VALIDATION
    // =========================================================================
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('category_id')
            ->allowEmptyString('category_id');

        $validator
            ->integer('brand_id')
            ->allowEmptyString('brand_id');

        // name: required, 2-150 chars
        $validator
            ->scalar('name')
            ->minLength('name', 2, 'Product name must be at least 2 characters')
            ->maxLength('name', 150)
            ->requirePresence('name', 'create')
            ->notEmptyString('name', 'Product name is required');

        // slug: auto-generated by SlugBehavior, but validate format if manually set
        $validator
            ->scalar('slug')
            ->maxLength('slug', 150)
            ->regex('slug', '/^[a-z0-9\-]+$/', 'Slug can only contain lowercase letters, numbers and hyphens')
            ->allowEmptyString('slug'); // Not required — Slug behavior generates it

        // sku: required, uppercase enforced by Entity mutator
        $validator
            ->scalar('sku')
            ->maxLength('sku', 50)
            ->requirePresence('sku', 'create')
            ->notEmptyString('sku', 'SKU is required');

        // price: decimal, must be >= 0
        $validator
            ->decimal('price')
            ->greaterThanOrEqual('price', 0, 'Price cannot be negative')
            ->requirePresence('price', 'create')
            ->notEmptyString('price', 'Price is required');

        // stock: integer >= 0
        $validator
            ->integer('stock')
            ->greaterThanOrEqual('stock', 0, 'Stock cannot be negative')
            ->notEmptyString('stock');

        $validator
            ->scalar('description')
            ->allowEmptyString('description');

        return $validator;
    }

    // =========================================================================
    // RULES CHECKER
    // =========================================================================
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        // existsIn: category_id must reference an existing category row
        $rules->add($rules->existsIn(['category_id'], 'Categories'), [
            'errorField' => 'category_id',
            'message'    => 'Please select a valid category.',
        ]);

        // existsIn: brand_id must reference an existing brand row
        $rules->add($rules->existsIn(['brand_id'], 'Brands'), [
            'errorField' => 'brand_id',
            'message'    => 'Please select a valid brand.',
        ]);

        // isUnique: SKU must be unique across all products
        $rules->add($rules->isUnique(['sku']), 'uniqueSku', [
            'errorField' => 'sku',
            'message'    => 'This SKU is already in use by another product.',
        ]);

        return $rules;
    }

    // =========================================================================
    // CUSTOM FINDERS — Phase 5
    // =========================================================================

    /**
     * findAvailable() — In-stock products only.
     * Usage: $this->Products->find('available')
     */
    public function findAvailable(SelectQuery $query, array $options): SelectQuery
    {
        return $query
            ->where(['Products.stock >' => 0]);
    }

    /**
     * findByCategory() — Products in a specific category.
     * Usage: $this->Products->find('byCategory', ['category_id' => 5])
     */
    public function findByCategory(SelectQuery $query, array $options): SelectQuery
    {
        if (empty($options['category_id'])) {
            return $query;
        }
        return $query->where(['Products.category_id' => $options['category_id']]);
    }

    /**
     * findPriceRange() — Products within a price range.
     * Usage: $this->Products->find('priceRange', ['min' => 100, 'max' => 500])
     */
    public function findPriceRange(SelectQuery $query, array $options): SelectQuery
    {
        if (!empty($options['min'])) {
            $query->where(['Products.price >=' => $options['min']]);
        }
        if (!empty($options['max'])) {
            $query->where(['Products.price <=' => $options['max']]);
        }
        return $query;
    }

    /**
     * findLowStock() — Products with stock at or below a threshold.
     * Usage: $this->Products->find('lowStock', ['threshold' => 5])
     */
    public function findLowStock(SelectQuery $query, array $options): SelectQuery
    {
        $threshold = $options['threshold'] ?? 5;
        return $query
            ->where(['Products.stock <=' => $threshold])
            ->orderBy(['Products.stock' => 'ASC']);
    }

    /**
     * findSearch() — Full text search across name, description, sku.
     * Usage: $this->Products->find('search', ['term' => 'vitamin'])
     */
    public function findSearch(SelectQuery $query, array $options): SelectQuery
    {
        $term = $options['term'] ?? '';
        if (!empty($term)) {
            $like = '%' . $term . '%';
            $query->where([
                'OR' => [
                    'Products.name LIKE'        => $like,
                    'Products.sku LIKE'         => $like,
                    'Products.description LIKE' => $like,
                ]
            ]);
        }
        return $query;
    }

    /**
     * Model.beforeFind — Phase 10
     *
     * Fires before every SELECT query on Products.
     * SoftDeleteBehavior already adds deleted_at IS NULL, but this is
     * where you'd add additional global filters.
     */
    public function beforeFind(EventInterface $event, SelectQuery $query, ArrayObject $options, bool $primary): void
    {
        Log::debug('[PHASE 10] Model.beforeFind — Products query intercepted');
    }

    /**
     * Model.beforeMarshal — Phase 10
     *
     * Normalize product data before entity creation.
     */
    public function beforeMarshal(EventInterface $event, ArrayObject $data, ArrayObject $options): void
    {
        Log::debug('[PHASE 10] Model.beforeMarshal — Products data being marshalled');

        // Trim product name
        if (!empty($data['name'])) {
            $data['name'] = trim($data['name']);
        }

        // Uppercase SKU
        if (!empty($data['sku'])) {
            $data['sku'] = strtoupper(trim($data['sku']));
        }

        // Default stock to 0 if not set
        if (!isset($data['stock'])) {
            $data['stock'] = 0;
        }
    }

    /**
     * Model.beforeRules — Phase 10
     */
    public function beforeRules(EventInterface $event, EntityInterface $entity, ArrayObject $options, string $operation): void
    {
        Log::debug(sprintf('[PHASE 10] Model.beforeRules — Products (operation: %s)', $operation));
    }

    /**
     * Model.afterRules — Phase 10
     */
    public function afterRules(EventInterface $event, EntityInterface $entity, ArrayObject $options, bool $result, string $operation): void
    {
        Log::debug(sprintf('[PHASE 10] Model.afterRules — Products rules %s', $result ? 'PASSED' : 'FAILED'));
    }

    /**
     * Model.beforeSave — Phase 10
     *
     * Set defaults, validate business logic before SQL.
     */
    public function beforeSave(EventInterface $event, EntityInterface $entity, ArrayObject $options): void
    {
        Log::debug(sprintf(
            '[PHASE 10] Model.beforeSave — Product %s (isNew: %s)',
            $entity->name ?? 'N/A',
            $entity->isNew() ? 'yes' : 'no'
        ));
    }

    /**
     * afterSave() — Phase 10: Invalidate caches + dispatch Product.lowStock.
     *
     * INTERVIEW: "I check the stock level after every save. If it drops
     *   below the threshold, I dispatch Product.lowStock. The listener
     *   will alert the procurement team without the controller knowing."
     */
    public function afterSave(EventInterface $event, EntityInterface $entity, ArrayObject $options): void
    {
        \Cake\Cache\Cache::delete('dashboard_total_products', 'redis');

        // Phase 10: Dispatch Product.lowStock if stock is below threshold
        $lowStockThreshold = 5;
        if (isset($entity->stock) && $entity->stock <= $lowStockThreshold && $entity->stock >= 0) {
            EventManager::instance()->dispatch(new Event(
                DomainEvents::PRODUCT_LOW_STOCK,
                $this,
                ['product' => $entity, 'threshold' => $lowStockThreshold]
            ));
        }
    }

    /**
     * beforeDelete() — Log product deletion before soft-delete runs.
     */
    public function beforeDelete(EventInterface $event, EntityInterface $entity, ArrayObject $options): void
    {
        Log::info(sprintf(
            '[PHASE 10] Model.beforeDelete — Product %s (ID: %d) being deleted',
            $entity->name ?? 'N/A',
            $entity->id ?? 0
        ));
    }

    /**
     * Model.afterDelete — Phase 10
     *
     * Cleanup after product deletion.
     */
    public function afterDelete(EventInterface $event, EntityInterface $entity, ArrayObject $options): void
    {
        Log::info(sprintf(
            '[PHASE 10] Model.afterDelete — Product %s deleted',
            $entity->name ?? 'N/A'
        ));

        \Cake\Cache\Cache::delete('dashboard_total_products', 'redis');
    }
}
